### ISSUE TITLE
The Master VM of the cluster should be configured to Allow full access to all Cloud APIs

### ISSUE THREAD

**Issue by bdalati** [grubwieser/Datalake-training#13]
Cloud API access scopes
Allow full access to all Cloud APIs

This can be done manually by user. or i can research tomorrow how to automate it in a configuration script

**Comment by AmritRaj23** [comment]
Assigning to a pre-configured service account should do the trick when creating the cluster.

**Comment by bdalati** [comment]
I updated the yaml file (sent via chat) to  Allow full access to all Cloud APIs
please update the Yaml file hosted on your private Bucket
