### ISSUE TITLE
1_Data_Engineer.ipynb

### ISSUE THREAD

**Issue by bdalati** [grubwieser/Datalake-training#7]
1)  !gsutil cat -h -r 0-1000 gs://datalake-vol2-data/dataset/fraud_data.csv   wrong data set here
2) please update bucket path to gs://2ca8b8fa-652a-11eb-8084-88e9fe60c70e

2) when executing 
table = project_id[0] + ":" + bq_table_path
df_transaction_data_from_bq = spark.read \
.format("bigquery") \
.option("table", table) \
.load()

you get error : java.lang.ClassNotFoundException: Failed to find data source: bigquery.

**Comment by bdalati** [comment]
solved.
please update the following Yaml file in the shared bucket
 

clusterName: CLUSTER_NAME
config:
  softwareConfig:
    imageVersion: 1.5-ubuntu18
    optionalComponents:
    - ANACONDA
    - JUPYTER
    properties:
      spark:spark.jars: gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.18.0.jar,gs://spark-lib/bigquery/spark-bigquery-latest.jar
  masterConfig:
    numInstances: 1
    machineTypeUri: n1-standard-4
    diskConfig:
      bootDiskType: pd-standard
      bootDiskSizeGb: 500
      numLocalSsds: 0
  workerConfig:
    numInstances: 2
    machineTypeUri: n1-standard-4
    diskConfig:
      bootDiskType: pd-standard
      bootDiskSizeGb: 500
      numLocalSsds: 0

**Comment by grubwieser** [comment]
done
